### ISSUE TITLE
Adicionar dados do paciente na resposta HTTP da rota de POST

### ISSUE THREAD

**Issue by lucasmedeiros** [joeberth/doctorMe#2]
Opa Joeberth, tudo bom? Estava analisando o seu projeto, e percebi que, ao fazer uma requisição `POST /patient` válida, apenas é retornado um valor:

```json
{ "success": true }
```

## Onde

[Arquivo de rotas](https://github.com/joeberth/doctorMe/blob/master/backend/src/routes/index.ts#L26)

## Sugestão de implementação

Poderia ser retornado juntamente os dados do paciente que acabou de ser cadastrado, que ficaria algo assim:

```json
{
    "success": true,
    "patient": {
        "name": "Lucas",
        "age": 22
    }
}
```

**Comment by joeberth** [comment]
Perfeito, valeu.
