### ISSUE TITLE
Sugestão para componente Carrossel

### ISSUE THREAD

**Issue by AramisAraujo** [joeberth/doctorMe#5]
Olá, notei que no readme mencionou um componente para carrossel. Estou sugerindo que utilize o [react-responsive-carousel](https://www.npmjs.com/package/react-responsive-carousel). Já utilizei num projeto e funcionou bem :) .

**Comment by joeberth** [comment]
Primeira, terminei optando por outro modo onde o carousel nao fazia mais sentido na aplicaçao, valeu!
