### ISSUE TITLE
Separação de dados em outro arquivo

### ISSUE THREAD

**Issue by LucasCBrasil** [joeberth/doctorMe#7]
Vi que já tem alguns pacientes teste no próprio arquivo de rotas no backend, sugiro que esses dados sejam colocados em um arquivo separado, facilitando a organização e o manuseio desses dados, adição de novos pacientes, bem como por ser uma boa prática.

**Comment by joeberth** [comment]
Tranquilo, Lucas. Fiz o backend em psql, pretendo subir e deixar alguns dados já salvos =D
